services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always
    networks:
      - quizzap

  backend:
    container_name: quizzap_backend
    env_file:
      - backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - ENV=dev
    restart: always
    command: bash -c "alembic upgrade head && python main.py --env dev"
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - quizzap
  
  database:
    container_name: quizzap_database
    image: mysql:latest
    env_file:
      - backend/.env
    ports:  
      - 3306:3306
    volumes:
      - quizzap_database:/var/lib/mysql
    networks:
      - quizzap

  phpmyadmin:
    container_name: quizzap_phpmyadmin
    image: phpmyadmin
    env_file:
      - backend/.env
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: quizzap_database
      PMA_PORT: 3306
      # PMA_ABSOLUTE_URI: /phpmyadmin/
    restart: always
    networks:
      - quizzap

networks:
  quizzap:
    driver: bridge

volumes:
  quizzap_database:
