services:
  backend:
    container_name: quizzap_backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=dev
    restart: always
    command: bash -c "alembic upgrade head && python main.py --env dev"
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - quizzap
    volumes:
      - quizzap_data:/app/data # Ensure SQLite database file is shared via a volume

  phpliteadmin:
    image: linuxserver/phpliteadmin
    container_name: phpliteadmin
    ports:
      - "8080:80"
    environment:
      - PUID=1000          # Replace with your user ID
      - PGID=1000          # Replace with your group ID
      - TZ=Etc/UTC         # Replace with your timezone
      - PASSWORD=root
    volumes:
      - quizzap_data:/config/db # Point phpLiteAdmin to the shared volume
    restart: unless-stopped
    networks:
      - quizzap

networks:
  quizzap:

volumes:
  quizzap_data:
