"""add question timelimit

Revision ID: bbef3844f359
Revises: 600ee4505ae0
Create Date: 2024-11-24 16:30:31.036820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbef3844f359'
down_revision: Union[str, None] = '600ee4505ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('time_limit', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'time_limit')
    # ### end Alembic commands ###
